#!/usr/bin/env node

/**
 * Generate `src/core/IO/VideoFont.ts` from 6502-PICOVDP's font source.
 *
 *   npm run sync:font                  write VideoFont.ts
 *   npm run sync:font -- --check       write nothing; fail if VideoFont.ts differs
 *
 *   PICOVDP_REPO   the 6502-PICOVDP checkout, if not ../../C/6502-PICOVDP from
 *                  this repository (the layout 6502-PICOVDP's PICOVDP_EMULATOR
 *                  assumes the other way round)
 *
 * The built-in font (VDP-SPEC §7) belongs to the card, and the card's source of
 * truth is 6502-PICOVDP: `fonts/cp437-6x8.bin`, whose SHA-256 the spec makes
 * normative. The emulator carries a generated copy so that it builds and tests
 * with no sibling checkout, and this script is the only thing that writes it.
 *
 * The commit recorded is the one that last changed the font file, not the
 * checkout's HEAD: PICOVDP moves on for reasons that have nothing to do with the
 * font, and `--check` should keep passing while the font does not change. A
 * checkout whose font was last changed at another commit is reported as that,
 * with both commits named — run this without `--check` to take the new font,
 * or check out the one recorded.
 *
 * A dirty PICOVDP tree is refused either way: the bytes on disk would not be
 * the bytes at any commit, and the header would say they were.
 */

import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative, resolve } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PICOVDP = resolve(process.env.PICOVDP_REPO ?? join(ROOT, '..', '..', 'C', '6502-PICOVDP'))
const REPOSITORY = 'acwright/6502-PICOVDP'
const SOURCE_PATH = 'fonts/cp437-6x8.bin'
const FONT_BYTES = 2048
const OUTPUT = join(ROOT, 'src', 'core', 'IO', 'VideoFont.ts')

function main() {
  const check = process.argv.slice(2).includes('--check')

  const source = join(PICOVDP, SOURCE_PATH)
  if (!existsSync(source)) fail(`no ${SOURCE_PATH} in ${PICOVDP} (set PICOVDP_REPO)`)

  const dirty = git('status', '--porcelain')
  if (dirty) fail(`${PICOVDP} has uncommitted changes; commit or stash them first:\n${dirty}`)

  const bytes = readFileSync(source)
  if (bytes.length !== FONT_BYTES) {
    fail(`${SOURCE_PATH} is ${bytes.length} bytes; font $00 is ${FONT_BYTES} (VDP-SPEC §7)`)
  }
  const commit = git('log', '-1', '--format=%H', '--', SOURCE_PATH)
  if (!commit) fail(`${SOURCE_PATH} is not committed in ${PICOVDP}`)
  const sha256 = createHash('sha256').update(bytes).digest('hex')

  const generated = render(bytes, { commit, sha256 })

  if (!check) {
    writeFileSync(OUTPUT, generated)
    console.log(`${relative(ROOT, OUTPUT)}: ${REPOSITORY} ${SOURCE_PATH} at ${commit.slice(0, 7)}, SHA-256 ${sha256.slice(0, 12)}…`)
    return
  }

  const committed = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : ''
  if (committed === generated) {
    console.log(`${relative(ROOT, OUTPUT)} is ${SOURCE_PATH} at ${commit.slice(0, 7)} (SHA-256 ${sha256.slice(0, 12)}…)`)
    return
  }
  const recorded = /commit: '([0-9a-f]{40})'/.exec(committed)?.[1]
  if (recorded && recorded !== commit) {
    fail(
      `${relative(ROOT, OUTPUT)} was generated from ${SOURCE_PATH} at ${recorded.slice(0, 7)}, ` +
        `but in ${PICOVDP} it was last changed at ${commit.slice(0, 7)}. ` +
        `Check out ${recorded.slice(0, 7)} there, or run \`npm run sync:font\` to take the new font.`
    )
  }
  fail(`${relative(ROOT, OUTPUT)} differs from what ${SOURCE_PATH} at ${commit.slice(0, 7)} generates — run \`npm run sync:font\``)
}

function render(bytes, { commit, sha256 }) {
  const hex = (value) => '0x' + value.toString(16).padStart(2, '0')
  const rows = []
  for (let glyph = 0; glyph < FONT_BYTES / 8; glyph++) {
    const cells = Array.from(bytes.subarray(glyph * 8, glyph * 8 + 8), hex).join(', ')
    rows.push(`  ${cells}, // $${glyph.toString(16).toUpperCase().padStart(2, '0')}`)
  }
  return `// GENERATED by scripts/sync-font.mjs — do not edit. Run \`npm run sync:font\`.
//
// Source:  ${REPOSITORY} ${SOURCE_PATH}
// Commit:  ${commit}
// SHA-256: ${sha256}

/**
 * Font \`$00\` (VDP-SPEC §7): CP437, 6 × 8. 256 glyphs of 8 row bytes, glyph *n*
 * at offset *n* × 8, b7 the leftmost pixel and b1:0 always 0.
 *
 * The same bytes 6502-BIOS v1.x keeps at \`$B800\` (\`Chars.asm\`); the card
 * writes them to \`$0800\` at reset and on a \`FONT\` command.
 */
export const FONT_6X8_CP437: Uint8Array = Uint8Array.from([
${rows.join('\n')}
])

/** Where \`FONT_6X8_CP437\` came from; \`sync-font.mjs --check\` holds it to that. */
export const FONT_SOURCE = {
  repository: '${REPOSITORY}',
  path: '${SOURCE_PATH}',
  commit: '${commit}',
  sha256: '${sha256}'
} as const
`
}

function git(...args) {
  return execFileSync('git', args, { cwd: PICOVDP, encoding: 'utf8' }).trim()
}

function fail(message) {
  console.error(`sync-font: ${message}`)
  process.exit(1)
}

main()
